ALTER TABLE users ADD COLUMN IF NOT EXISTS risk_profile TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS savings_goal TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN NOT NULL DEFAULT FALSE;
